// Generated by CoffeeScript 1.6.3
(function() {
  var assert, client, restify;

  assert = require('assert');

  restify = require('restify');

  client = restify.createJsonClient({
    url: 'http://localhost:8000',
    version: '1.0.0'
  });

  client.get('/snapshots/asdf', function(err, req, res, obj) {
    assert.ifError(err);
    return console.log('Server returned: %j', obj);
  });

}).call(this);
